apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# commonLabels:
#   app.kubernetes.io/managed-by: Kustomize
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: Kustomize
resources:
  - ./metallb/pool.yaml
