repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
---
releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.8.0
    values:
      - ./values/longhorn.values.yaml

  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.9

  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.27.0
    values:
      - ./values/pihole.values.yaml

  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.12.0
    values:
      - ./values/nginx-internal.values.yaml

  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.0.1
    values:
      - ./values/externaldns.values.yaml

  - name: cert-manager
    namespace: cert-manager
    version: 1.16.3
    chart: jetstack/cert-manager
    values:
      - ./values/cert-manager.values.yaml
